# Generated by Django 3.2.7 on 2021-09-28 05:32

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=200, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
